spring.datasource.url=jdbc:mariadb://58ea917d-11a0-4864-979f-34a7070d9edc.ma.bw-cloud-instance.org:3307/cooked-test
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=cooked1
spring.datasource.password=FUIAjjYBwc1mTOn3

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
server.port=8081

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cooked.eu.auth0.com/

# auth0 configuration (okta starter)
okta.oauth2.issuer=${spring.security.oauth2.resourceserver.jwt.issuer-uri}
okta.oauth2.audience=https://cooked.api
