ALTER TABLE product ADD COLUMN IF NOT EXISTS ingredients LONGTEXT;
ALTER TABLE product ADD COLUMN IF NOT EXISTS steps LONGTEXT;
ALTER TABLE product MODIFY COLUMN ingredients LONGTEXT;
ALTER TABLE product MODIFY COLUMN steps LONGTEXT;
