ALTER TABLE product ADD COLUMN IF NOT EXISTS ingredients LONGTEXT;
ALTER TABLE product ADD COLUMN IF NOT EXISTS steps LONGTEXT;
ALTER TABLE product MODIFY COLUMN ingredients LONGTEXT;
ALTER TABLE product MODIFY COLUMN steps LONGTEXT;
ALTER TABLE product ADD COLUMN IF NOT EXISTS created_by_email VARCHAR(320);
ALTER TABLE product MODIFY COLUMN category LONGTEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(1000);
ALTER TABLE users ADD COLUMN IF NOT EXISTS oauth_id VARCHAR(255);
CREATE TABLE IF NOT EXISTS user_favorites (
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, product_id)
);
